# NOTE: while developing, switch to local volumes and target to production

version: "3"
services:
  backend:
    container_name: bookclub-voting-backend
    build:
      context: ./backend
      target: production
      # target: development
    volumes:
      - backend_node_module:/app/node_modules
      # - ./backend:/app/
    # remove for production, only for direct API testing
    # ports:
    #   - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    container_name: bookclub-voting-frontend
    build:
      context: ./frontend
      target: production
      # target: development
    volumes:
      - frontend_node_module:/app/node_modules
      # - ./frontend:/app/
    env_file:
      - .env
    ports:
      - "8080:8080"
    links:
      - backend

  postgres:
    container_name: postgres
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  backend_node_module:
  frontend_node_module:
  pgdata:
