# NOTE: while developing, switch to local volumes and target to production

version: "3"
services:
  backend:
    build:
      context: ./backend
      # target: production
      target: development
    volumes:
      # - backend_node_module:/app/node_modules
      - ./backend:/app/
    # remove for production, only for direct API testing
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - PORT=3000
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      # target: production
      target: development
    volumes:
      # - frontend_node_module:/app/node_modules
      - ./frontend:/app/
    env_file:
      - .env
    environment:
      - PORT=8080
      - BACKEND_URL=http://backend:3000
    ports:
      - 8080:8080

  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  backend_node_module:
  frontend_node_module:
  pgdata:
